# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Continuous Integration"

on:
  - "pull_request"
  - "push"

jobs:

  continuous-integration:
    name: "Continuous Integration"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"

        dependencies:
          - "highest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          php-version: "${{ matrix.php-version }}"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v1"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('**/composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"

      - name: "Install dependencies with composer"
        run: "composer install --no-interaction"

      - name: "Run static code analysis with phpstan/phpstan"
        run: "composer phpstan"
        
      - name: "Run tests with phpunit/phpunit"
        run: "composer phpunit"

      - name: "Run coding standard checks with squizlabs/php_codesniffer"
        run: "composer cs-check"

      #- name: "Archive code coverage results"
      #  uses: "actions/upload-artifact@v1"
      #  with:
      #    name: "build"
      #    path: "build"

      #- name: "Upload test coverage to coveralls"
      #  continue-on-error: true
      #  run: "php vendor/bin/php-coveralls -v"
      #  working-directory: "generator"
      #  env:
      #    COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      #    COVERALLS_RUN_LOCALLY: 1
